version: '3.7'

volumes:
  mysql56_volume:
    name: MySql56-Volume
  mysql57_volume:
    name: MySql57-Volume
  mysql80_volume:
    name: MySql80-Volume
  mariadb101_volume:
    name: MariaDB101-Volume
  mariadb102_volume:
    name: MariaDB102-Volume
  mariadb103_volume:
    name: MariaDB103-Volume
  mariadb104_volume:
    name: MariaDB104-Volume

services:
  reverse-proxy:
    image: traefik:v2.2
    container_name: "reverse-proxy"
    restart: always
    network_mode: bridge
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./traefik.toml:/traefik.toml
      - ./configuration/:/configuration/
      - ${SSL_CERTIFICATES_DIR}:/certs/

  mysql56:
    container_name: mysql56
    image: mysql:5.6
    restart: always
    labels:
      - traefik.enable=false
    network_mode: bridge
    ports:
      - 3356:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    volumes:
      - mysql56_volume:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf

  mysql57:
    container_name: mysql57
    image: mysql:5.7
    restart: always
    labels:
      - traefik.enable=false
    network_mode: bridge
    ports:
      - 3357:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    volumes:
      - mysql57_volume:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf

  mysql80:
    container_name: mysql80
    image: mysql:8.0
    restart: always
    labels:
      - traefik.enable=false
    network_mode: bridge
    ports:
      - 3380:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    volumes:
      - mysql80_volume:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf

  mariadb101:
    container_name: mariadb101
    image: bitnami/mariadb:10.1
    user: root
    restart: always
    labels:
      - traefik.enable=false
    network_mode: bridge
    ports:
      - 33101:3306
    environment:
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - mariadb101_volume:/bitnami/mariadb
      - ./my.cnf:/etc/my.cnf

  mariadb102:
    container_name: mariadb102
    image: bitnami/mariadb:10.2
    user: root
    restart: always
    labels:
      - traefik.enable=false
    network_mode: bridge
    ports:
      - 33102:3306
    environment:
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - mariadb102_volume:/bitnami/mariadb
      - ./my.cnf:/etc/my.cnf

  mariadb103:
    container_name: mariadb103
    image: bitnami/mariadb:10.3
    user: root
    restart: always
    labels:
      - traefik.enable=false
    network_mode: bridge
    ports:
      - 33103:3306
    environment:
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - mariadb103_volume:/bitnami/mariadb
      - ./my.cnf:/etc/my.cnf

  mariadb104:
    container_name: mariadb104
    image: bitnami/mariadb:10.4
    user: root
    restart: always
    labels:
      - traefik.enable=false
    network_mode: bridge
    ports:
      - 33104:3306
    environment:
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - mariadb104_volume:/bitnami/mariadb
      - ./my.cnf:/etc/my.cnf

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpmyadmin-http.rule=Host(`phpmyadmin.docker.local`)
      - traefik.http.routers.phpmyadmin-http.entrypoints=http
    network_mode: bridge
    depends_on:
      - reverse-proxy
      - mysql56
      - mysql57
      - mysql80
      - mariadb101
      - mariadb102
      - mariadb103
      - mariadb104
    links:
      - mysql56:mysql56
      - mysql57:mysql57
      - mysql80:mysql80
      - mariadb101:mariadb101
      - mariadb102:mariadb102
      - mariadb103:mariadb103
      - mariadb104:mariadb104
    environment:
      - PMA_HOSTS=mysql57,mysql80,mysql56,mariadb101,mariadb102,mariadb103,mariadb104
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_ABSOLUTE_URI=http://phpmyadmin.docker.local/
    volumes:
      - /sessions

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:v1.0.1
    restart: always
    network_mode: bridge
    ports:
      - 1025:1025
      - 8025:8025