[global]
  sendAnonymousUsage = false

[log]
  level = "WARN" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
  format = "common"

[serversTransport]
  insecureSkipVerify = true

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"
	
  [entryPoints.livereload-http]
    address = ":35729"

  [entryPoints.livereload-https]
    address = ":35730"

[providers]
  [providers.file]
    directory = "/configuration/"
    watch = true

  [providers.docker]
    exposedbydefault = false

[api]
  dashboard = true
