# SSL certificates for development
# $ mkcert example.com www.example.com example-2.com www.example-2.com
#
# DEVELOPMENT:
# $ docker-compose -f docker-compose.yml -f docker-compose-dev.yml up -d
#
# PRODUCTION:
# $ docker-compose up -d
#
# MacOS (development only)
# docker-sync-stack start

version: '3.7'
services:
  php-apache:
    container_name: example.com
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        # needed for the build stage
        # Install memcached inside container if needed. Better to use external Memcached container and only have
        # php extension to connect to it
        - MEMCACHED=0
    restart: always
    labels:
      - traefik.enable=true

      - traefik.http.routers.example-unsecure.rule=Host(`example.com`, `example-2.com`) || Host(`wwww.example.com`, `www.example-2.com`)
      - traefik.http.routers.example-unsecure.entrypoints=web
      - traefik.http.routers.example-unsecure.service=example-service-unsecure
      - traefik.http.services.example-service-unsecure.loadbalancer.server.port=80
      - traefik.http.services.example-service-unsecure.loadbalancer.server.scheme=http

      - traefik.http.routers.example-secure.rule=Host(`example.com`, `example-2.com`) || Host(`www.example.com`, `www.example-2.com`)
      - traefik.http.routers.example-secure.entrypoints=websecure
      - traefik.http.routers.example-secure.tls=true
      - traefik.http.routers.example-secure.service=example-service
      - traefik.http.services.example-service.loadbalancer.server.port=443
      - traefik.http.services.example-service.loadbalancer.server.scheme=https
    # Must add extra_hosts to be written to /etc/hosts - otherwise containerized application can not curl itself
    extra_hosts:
      - "example.com www.example.com example-2.com www.example-2.com:127.0.0.1"
#    links:
#      - memcached
#      - redis
#      - elasticsearch
    external_links:
      - mysql57:mysql
    network_mode: bridge
    volumes:
      - .:/var/www/html
      - /misc/share/ssl:/certs
      - ./docker/virtual-host.conf:/etc/apache2/sites-enabled/virtual-host.conf

#  redis:
#    image: redis:latest
#    network_mode: bridge
#    labels:
#      - traefik.enable=false
#    restart: always

#  memcached:
#    image: 'memcached:1.5'
#    network_mode: bridge
#    labels:
#      - traefik.enable=false
#    restart: always

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
#    environment:
#      http.host: 0.0.0.0
#      transport.host: localhost
#      network.host: 0.0.0.0
#      xpack.security.enabled: "false"
#      indices.query.bool.max_clause_count: 10240
#      ES_JAVA_OPTS: -Xms512m -Xmx512m
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    restart: always
#    network_mode: bridge